### ISSUE TITLE
Does overlay only support RV32?

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-overlay#14]
I saw there is relocation for 32-bit overlay plt entry address (R_RISCV_OVLPLT32), does it means overlay only support rv32?

**Comment by oferShinaar** [comment]
yes, the vast usage of overlay is very small embedded devices (small IoT). Usually, 64bit machines will have bigger memory and/or mmu.
But the "SW Standard/spec" doesn't limit it to 32/64 or any target. The implementation design for RISCV do limit it to 32bit

**Comment by kito-cheng** [comment]
Thanks for clarification :)
