### ISSUE TITLE
Relaxations concern 

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-overlay#15]
https://github.com/riscv/riscv-overlay/blob/master/docs/overlay-hld.adoc#2727-relaxations

I think it's unsafe transformer from `lui t5, 0; addi t5, t5, 3` to `addi t5, zero, 3; jalr ra, 0(t6)`, the later one will corrupt the `ra` but original one won't.

**Comment by craigblackmore** [comment]
> https://github.com/riscv/riscv-overlay/blob/master/docs/overlay-hld.adoc#2727-relaxations
> 
> I think it's unsafe transformer from `lui t5, 0; addi t5, t5, 3` to `addi t5, zero, 3; jalr ra, 0(t6)`, the later one will corrupt the `ra` but original one won't.

Thanks, Kito. The relaxation transforms `lui / addi` to `addi`. The `jalr` got copied in by mistake, I have removed it now.

**Comment by oferShinaar** [comment]
fix is merged
